### ISSUE TITLE
Speedup for large ncdu files ?

### ISSUE THREAD

**Issue by pschonmann** [yaroslaff/ncdu-compare#2]
Tried to compare large ncdu files ... it takes ages :)

pschonmann@E495:~/temp/$ wc -l ncdu_2023-02-*
  1449422 ncdu_2023-02-09_103801
  1451621 ncdu_2023-02-10_223801

real	361m4.665s
user	358m49.615s
sys	1m16.661s

and hit ctrl+c to stop waiting

**Comment by yaroslaff** [comment]
new version (0.0.5. version is printed when -h/--help option used) works faster now. (from ~infinite time to 11 seconds on my computer)

**Comment by pschonmann** [comment]
Works flawlessly

```
pschonmann@E495:~/temp/glob$ time ncdu-compare 1.ascii 2.ascii > /dev/null

real	0m16.373s
user	0m15.022s
sys	0m1.331s
```
