### ISSUE TITLE
compare only dirs/files/both mode

### ISSUE THREAD

**Issue by pschonmann** [yaroslaff/ncdu-compare#3]
Hi, would be fine to compare only files/dirs/both with some --option [default both]

For example i want only compare files, but not directories, but sometimes vice versa

Here is example where "dupes" occurs
138851 /data/www/ftp_data_external/exp_documents/1422569840 (0 > 138851)
138851 /data/www/ftp_data_external/exp_documents/1422569840/373446.pdf (0 > 138851)

Is it possible ? At first look to output file from ncdu im not sure tell that row is folder or file. But looks like structured json file. Im not good at this python things :)

Mark it as feature request with low prio :D 
Anyway thanks and have a nice day.

**Comment by yaroslaff** [comment]
What if ncdu-compare will print type of file/dir, e.g.

```
138851 DIR /data/www/ftp_data_external/exp_documents/1422569840 (0 > 138851)
138851 FILE /data/www/ftp_data_external/exp_documents/1422569840/373446.pdf (0 > 138851)
```
If you want only files, you can just add `| grep FILE`.
Would this solve problem?

**Comment by pschonmann** [comment]
:1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: 
:1st_place_medal: AWESOME :1st_place_medal: 
:1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal:

**Comment by yaroslaff** [comment]
Done, try version v0.0.7 to see if it's working for you

**Comment by pschonmann** [comment]
It works ! Thank you so much !
