### ISSUE TITLE
Human-readable format of size

### ISSUE THREAD

**Issue by untitled99** [yaroslaff/ncdu-compare#4]
I ran it normally and got the results. As for the result, however, instead of in a human readable format, it show them in raw format, say:  (44447488 > 0)

I wonder is there any way to toggle around?

Thanks for the great work!

**Comment by yaroslaff** [comment]
What version do you use? Latest is 0.0.8:
~~~
 $ ncdu-compare -h
usage: ncdu-compare [-h] [-e ERROR] old new

Compare old and new ncdu dumps. ver. 0.0.8
~~~

and output format (right part) is human readable now:
~~~
1048576 FILE /home/xenon/repo/ncdu-compare/1M (0 => 1.05M (1.05M))
1048576 DIR /home/xenon/repo/ncdu-compare (101.87K => 1.15M (1.05M))
~~~

Please try to upgrade. Let me know if any issues with upgrading or after it.

**Comment by yaroslaff** [comment]
No answer for long time, I'm closing ticket. (reopen it if you still have any problems with ncdu-compare).
